### ISSUE TITLE
Launching it in AWS does not finish because snapshot IDs are not public or wrong

### ISSUE THREAD

**Issue by Fsero** [mesosphere/dcos-kubernetes-quickstart#8] opened 2017-09-12 07:22 UTC
When launching the quickstart in AWS it will hang in creating the BareServer autoscaling group due to instances incapable of getting the snapshot. In the Cloudformation template these are the ids listed:

 "SDBSnapshot": {
      "us-west-2": {"snap": "snap-00ae1a58"},
      "us-west-1": {"snap": "snap-2f2c1516"},
      "sa-east-1": {"snap": "snap-356b2302"},
      "us-east-1": {"snap": "snap-5f580f42"},
      "ap-southeast-1": {"snap": "snap-a7be23b6"},
      "ap-southeast-2": {"snap": "snap-e1f4bfed"},
      "ap-northeast-1": {"snap": "snap-b970ec81"},
      "eu-west-1": {"snap": "snap-056ada2d"},
      "eu-central-1": {"snap": "snap-2c830027"}
    }

but as the image attached shows, instances cannot launch due to this

![image](https://user-images.githubusercontent.com/1088313/30312904-be38a83a-979b-11e7-8faa-b776ffe5d665.png)

**Comment by spahl** [comment] 2017-09-13 20:11
Changing line 114 in the Makefile to "cent-os-7" or "coreos" should make it work. Testing and then submitting PR.

**Comment by Fsero** [comment] 2017-09-14 16:04
I tried that with the same results...

**Comment by MikeMichel** [comment] 2017-10-10 16:09
same here. changing the makefile does not help.

**Comment by spahl** [comment] 2017-10-11 15:22
We are looking into a fix

**Comment by pires** [comment] 2018-02-01 08:05
@spahl any updates on this?

**Comment by pires** [comment] 2018-03-16 08:18
@rimusz can you verify this, please?

**Comment by rimusz** [comment] 2018-03-16 08:32
sure

**Comment by rimusz** [comment] 2018-03-16 10:10
took another look to the issue, it was opened back in september 2017 when `quickstart` was based on `dcos-launch`, we moved to terraform based setup in december, which uses a bit different setup of the dc/os cluster. So I cannot reproduce the issue anymore. I would suggest to close it.

**Comment by pires** [comment] 2018-03-16 10:14
I will do so. There's also no more feedback from the people who faced this.

**Closed by pires** 2018-03-16 10:14 UTC
Labels: bug
